name: Deploy to GitHub Pages Repo

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"  # Specify your required Node version

      - name: Install dependencies and build
        run: |
          npm install
          npm run build  # This creates the dist folder

      - name: Clone GitHub Pages repository
        run: |
          git clone --depth 1 https://x-access-token:${{ secrets.ACTIONS_GITHUB_TOKEN }}@github.com/Edit-Mr/Edit-Mr.github.io.git
          
      - name: Copy build to pages repo root
        run: |
          cd Edit-Mr.github.io
          git rm -rf assets/  # Remove existing assets
          cd ..
          cp -rf dist/* Edit-Mr.github.io/  # Copy built files from dist to the pages repo

      - name: Commit and push changes
        run: |
          cd Edit-Mr.github.io
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Deploy from Edit-Mr/intro"
          git push
